# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 700)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("background-color:#FFBF00;")
        self.lblBaslik = QtWidgets.QLabel(Form)
        self.lblBaslik.setGeometry(QtCore.QRect(40, 10, 611, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblBaslik.setFont(font)
        self.lblBaslik.setStyleSheet("color:white")
        self.lblBaslik.setObjectName("lblBaslik")
        self.btnHesapla = QtWidgets.QPushButton(Form)
        self.btnHesapla.setGeometry(QtCore.QRect(190, 380, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnHesapla.setFont(font)
        self.btnHesapla.setStyleSheet("background-color:black;color:white")
        self.btnHesapla.setObjectName("btnHesapla")
        self.btnTemizle = QtWidgets.QPushButton(Form)
        self.btnTemizle.setGeometry(QtCore.QRect(370, 380, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnTemizle.setFont(font)
        self.btnTemizle.setStyleSheet("background-color:white;color:black")
        self.btnTemizle.setObjectName("btnTemizle")
        self.lblYontem = QtWidgets.QLabel(Form)
        self.lblYontem.setGeometry(QtCore.QRect(80, 300, 201, 53))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblYontem.setFont(font)
        self.lblYontem.setStyleSheet("color:#DF013A")
        self.lblYontem.setObjectName("lblYontem")
        self.cmbBxYontem = QtWidgets.QComboBox(Form)
        self.cmbBxYontem.setGeometry(QtCore.QRect(310, 300, 309, 44))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbBxYontem.setFont(font)
        self.cmbBxYontem.setStyleSheet("background-color:white")
        self.cmbBxYontem.setObjectName("cmbBxYontem")
        self.cmbBxYontem.addItem("")
        self.cmbBxYontem.addItem("")
        self.cmbBxYontem.addItem("")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 90, 191, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblDenklem1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblDenklem1.setFont(font)
        self.lblDenklem1.setStyleSheet("color:black")
        self.lblDenklem1.setObjectName("lblDenklem1")
        self.verticalLayout.addWidget(self.lblDenklem1)
        self.lblDenklem2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblDenklem2.setFont(font)
        self.lblDenklem2.setStyleSheet("color:black")
        self.lblDenklem2.setObjectName("lblDenklem2")
        self.verticalLayout.addWidget(self.lblDenklem2)
        self.lblDenklem3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblDenklem3.setFont(font)
        self.lblDenklem3.setStyleSheet("color:black")
        self.lblDenklem3.setObjectName("lblDenklem3")
        self.verticalLayout.addWidget(self.lblDenklem3)
        self.lblDenklem4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblDenklem4.setFont(font)
        self.lblDenklem4.setStyleSheet("color:black")
        self.lblDenklem4.setObjectName("lblDenklem4")
        self.verticalLayout.addWidget(self.lblDenklem4)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 90, 311, 199))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lnEdtDenklem1 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtDenklem1.setFont(font)
        self.lnEdtDenklem1.setStyleSheet("background-color:white")
        self.lnEdtDenklem1.setObjectName("lnEdtDenklem1")
        self.verticalLayout_2.addWidget(self.lnEdtDenklem1)
        self.lnEdtDenklem2 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtDenklem2.setFont(font)
        self.lnEdtDenklem2.setStyleSheet("background-color:white")
        self.lnEdtDenklem2.setObjectName("lnEdtDenklem2")
        self.verticalLayout_2.addWidget(self.lnEdtDenklem2)
        self.lnEdtDenklem3 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtDenklem3.setFont(font)
        self.lnEdtDenklem3.setStyleSheet("background-color:white")
        self.lnEdtDenklem3.setObjectName("lnEdtDenklem3")
        self.verticalLayout_2.addWidget(self.lnEdtDenklem3)
        self.lnEdtDenklem4 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtDenklem4.setFont(font)
        self.lnEdtDenklem4.setStyleSheet("background-color:white")
        self.lnEdtDenklem4.setObjectName("lnEdtDenklem4")
        self.verticalLayout_2.addWidget(self.lnEdtDenklem4)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(320, 460, 151, 199))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lnEdtX = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtX.setFont(font)
        self.lnEdtX.setStyleSheet("background-color:white")
        self.lnEdtX.setReadOnly(True)
        self.lnEdtX.setObjectName("lnEdtX")
        self.verticalLayout_3.addWidget(self.lnEdtX)
        self.lnEdtY = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtY.setFont(font)
        self.lnEdtY.setStyleSheet("background-color:white")
        self.lnEdtY.setReadOnly(True)
        self.lnEdtY.setObjectName("lnEdtY")
        self.verticalLayout_3.addWidget(self.lnEdtY)
        self.lnEdtZ = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtZ.setFont(font)
        self.lnEdtZ.setStyleSheet("background-color:white")
        self.lnEdtZ.setReadOnly(True)
        self.lnEdtZ.setObjectName("lnEdtZ")
        self.verticalLayout_3.addWidget(self.lnEdtZ)
        self.lnEdtT = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lnEdtT.setFont(font)
        self.lnEdtT.setStyleSheet("background-color:white")
        self.lnEdtT.setReadOnly(True)
        self.lnEdtT.setObjectName("lnEdtT")
        self.verticalLayout_3.addWidget(self.lnEdtT)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(250, 460, 51, 201))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblx = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblx.setFont(font)
        self.lblx.setStyleSheet("color:black")
        self.lblx.setObjectName("lblx")
        self.verticalLayout_4.addWidget(self.lblx)
        self.lbly = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbly.setFont(font)
        self.lbly.setStyleSheet("color:black")
        self.lbly.setObjectName("lbly")
        self.verticalLayout_4.addWidget(self.lbly)
        self.lblz = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblz.setFont(font)
        self.lblz.setStyleSheet("color:black")
        self.lblz.setObjectName("lblz")
        self.verticalLayout_4.addWidget(self.lblz)
        self.lblt = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblt.setFont(font)
        self.lblt.setStyleSheet("color:black")
        self.lblt.setObjectName("lblt")
        self.verticalLayout_4.addWidget(self.lblt)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lnEdtDenklem1, self.lnEdtDenklem2)
        Form.setTabOrder(self.lnEdtDenklem2, self.lnEdtDenklem3)
        Form.setTabOrder(self.lnEdtDenklem3, self.btnHesapla)
        Form.setTabOrder(self.btnHesapla, self.btnTemizle)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Denklem Hesaplama"))
        self.lblBaslik.setText(_translate("Form", "Dört Bilinmeyenli Denklem Sistemlerini Çözme"))
        self.btnHesapla.setText(_translate("Form", "Hesapla"))
        self.btnTemizle.setText(_translate("Form", "Temizle"))
        self.lblYontem.setText(_translate("Form", "Yöntem Seç  :"))
        self.cmbBxYontem.setItemText(0, _translate("Form", "Cramer Yöntemi"))
        self.cmbBxYontem.setItemText(1, _translate("Form", "Gauss-Jordan Yöntemi"))
        self.cmbBxYontem.setItemText(2, _translate("Form", "Cholesky Yöntemi"))
        self.lblDenklem1.setText(_translate("Form", "1.Denklem  :"))
        self.lblDenklem2.setText(_translate("Form", "2.Denklem  :"))
        self.lblDenklem3.setText(_translate("Form", "3.Denklem  :"))
        self.lblDenklem4.setText(_translate("Form", "4.Denklem  :"))
        self.lblx.setText(_translate("Form", "x :"))
        self.lbly.setText(_translate("Form", "y :"))
        self.lblz.setText(_translate("Form", "z :"))
        self.lblt.setText(_translate("Form", "t :"))

